Mostly consistency but not proportionally as much as last time
DS-Homebrew/wiki pull request #25
Opened 2021-07-30 10:27 UTC by spellboundtriangle

Please read the changes and share your thoughts if you disagree with any of them or found any issues with my wording and such.

2021-07-30 11:22 UTC, lifehackerhansol requested changes
If there's any other mentions of Game Cards those should also be proper noun'd

2021-07-30 11:22 UTC, lifehackerhansol commented on pages/_en-US/ds-index/dsi-twl-firm.md
> +In version 1.4.0, RSA signatures in the DS game card whitelist aren't verified. This is a vulnerability that can be exploited, and it allows you to take access over the ARM9 processor. It requires ve
Game Card should be capitalized properly if we're going to use that term

2021-07-30 11:22 UTC, lifehackerhansol commented on pages/_en-US/ds-index/retail-roms.md
> +Though rare, there are DS game cards with NAND based saves: WarioWare DIY & Jam with the Band (USA)/Daigasso Band Brothers.
Same as above

2021-07-31 03:05 UTC, spellboundtriangle commented
Done, and edited contributing page for that.

2021-08-02 17:34 UTC, merged