Update custom DSi/3DS skins page
DS-Homebrew/wiki pull request #72
Opened 2022-08-14 05:08 UTC by spellboundtriangle

The current commit adds:
- Some edits
- Add a couple of missing backgrounds and icons
- Remove date_time_font image and add FontPaletteDateTime1-4 (for next release)
  - Not 100% certain on the validity of the default colors for the palette

This PR isn't yet complete. I'd like to add some things before merging, but I need to sleep soon and this has a fair amount of information that needs to be added, so I'm leaving it as a draft PR so I (or anyone else) can come back to it later to complete it.
Currently, the following needs to be added:
- [ ] `Date`/`Time`/`UsernameRender` and their defaults ([45cd452](https://github.com/DS-Homebrew/TWiLightMenu/commit/45cd45297f1446eb7a250eacae2360e9648be30f))
- [ ] Information on `[MACRO]` settings ([45cd452](https://github.com/DS-Homebrew/TWiLightMenu/commit/45cd45297f1446eb7a250eacae2360e9648be30f))
- [ ] Information on `FontPaletteTitlebox`/`Dialog`/`Overlay` and their defaults ([3583476](https://github.com/DS-Homebrew/TWiLightMenu/commit/35834762c8e9cd6530aee5dd056c03dfb325f60c))
- [ ] Information on custom/skin fonts themselves, maybe with some stuff on the Custom Fonts page, I'm not sure

2022-08-29 08:40 UTC, spellboundtriangle commented
I think I have everything done... I would appreciate if anyone would read over the changes and let me know if you disagree with anything, if anything was unclear, or if I missed anything.

I'm undrafting this, but it isn't quite ready to be merged, since releases don't have [8985b7e](https://github.com/DS-Homebrew/TWiLightMenu/commit/8985b7e37b8ed479fa35e68044c8afa7a0333bd3) yet. It can be merged whenever the next release is, I guess.

Also, I noticed that recent TWiLight Menu++ releases haven't really mentioned most of this stuff, which is fine since custom skins are kind of an obscured thing, but with this update it might be worth mentioning that some new stuff has recently come to TWiLight Menu++ skinning, in the notes of the next release.

2022-08-29 17:38 UTC, DieGo367 commented
> Any pixel that is transparent in one texture should be transparent in all of them, so that it's properly overwritten on change.

This is no longer the case for the `battery` and `volume` textures, since they now restore the background for the transparent pixels. Note that this still is the case for the shoulder textures in the `ui` folder, however.

Also, `FontPaletteName` was renamed to `FontPaletteUsername` for consistency.

2022-09-06 03:30 UTC, spellboundtriangle commented
Now that TWiLight Menu++ 25.3.0 has been released and announced, this should be okay to merge, assuming I didn't miss anything.

2022-10-09 20:52 UTC, NightScript370 requested changes
Other changes I'd like to see made to the page are not part of your PR and I will wait until this PR is done in order to change them. Although these issues are more apparent due to your PR, they've always been a part of the text. One example is run on sentences, which was (badly) disguised by not including commas. With the addition of the commas (which I prefer), although the sentence reading flows better, their length is now apparent.

However, again, that's outside the PR. These are the only changes I'd make within the scope of what you did.

2022-10-09 20:52 UTC, NightScript370 commented on pages/_en-US/twilightmenu/custom-fonts.md
> +You may add fonts to [custom DSi/3DS theme skins](custom-dsi-3ds-skins), which will override whatever is set in TWiLight Menu++ settings. These fonts go in the `font` folder, in the skin's root folde
I understand the way you wrote the sentence here is more consistent with the way the custom skins page is written, but within the context of this page, it's definitely weird. Perhaps try something of the sort to line your additions with the official page:

```md
### Skin-Dependent fonts
[Custom skins](custom-dsi-3ds-skins) for the Nintendo DSi/Nintendo 3DS themes can override the font setting for the general UI. These overrides are to be placed within the skin's `font` folder.
- Specific elements could have their font overridden, by titling the file according to the specifications set by the page above
- Delete the files within the skin in order to restore the font to whatever was specified in the TWiLight Menu++ settings
```

2022-10-12 05:12 UTC, NightScript370 commented
Actually, on further thoughts, since this is good enough and I don't want to add laborious work to what I'd already change in the future, I will merge as is.

2022-10-12 05:12 UTC, merged